alter table service_request drop foreign key FKft9yx7vxsvi6s25amj2tgv9dt;
alter table skill drop foreign key FKn93wnow98qmoisi6xut7keq00;
drop table if exists contact_details;
drop table if exists service_request;
drop table if exists skill;
create table contact_details (
        recruited_id integer not null auto_increment,
        company_phone integer,
        company_website varchar(255),
        contact_company varchar(255),
        recruiter_name varchar(255),
        primary key (recruited_id)
    );

    create table service_request (
        service_request_id integer not null GENERATED BY DEFAULT AS IDENTITY,
        company_profile VARCHAR(1000000),
        created_date datetime,
        cost_to_company varchar(255),
        dcrequirement bit,
        pgrequirement bit,
        ugrequirement bit,
        experience integer,
        job_location varchar(255),
        position varchar(255),
        time_to_join integer,
        job_description VARCHAR(1000000),,
        job_title varchar(255),
        contact_details_recruited_id integer,
        primary key (service_request_id)
    );
	
    create table skill (
        skill_id integer not null GENERATED BY DEFAULT AS IDENTITY,
        skill_name varchar(255),
        service_requestid integer not null,
        primary key (skill_id)
    );

    alter table service_request 
        add constraint FKft9yx7vxsvi6s25amj2tgv9dt 
        foreign key (contact_details_recruited_id) 
        references contact_details (recruited_id);

    alter table skill 
        add constraint FKn93wnow98qmoisi6xut7keq00 
        foreign key (service_requestid) 
        references service_request (service_request_id);